[package]
name = "message_broker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.3"
parking_lot = "0.12.1"
thiserror = "1.0.58"
